//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/MenuControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuControls"",
    ""maps"": [
        {
            ""name"": ""MenuControllerSupport"",
            ""id"": ""59746225-0068-4892-b8fd-1898045208ca"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""c5e9d300-5fef-4e1d-b4db-7d52aea19125"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d6fff2cf-f3aa-472f-91da-fe7e700331db"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MenuControllerSupport
        m_MenuControllerSupport = asset.FindActionMap("MenuControllerSupport", throwIfNotFound: true);
        m_MenuControllerSupport_Up = m_MenuControllerSupport.FindAction("Up", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MenuControllerSupport
    private readonly InputActionMap m_MenuControllerSupport;
    private IMenuControllerSupportActions m_MenuControllerSupportActionsCallbackInterface;
    private readonly InputAction m_MenuControllerSupport_Up;
    public struct MenuControllerSupportActions
    {
        private @MenuControls m_Wrapper;
        public MenuControllerSupportActions(@MenuControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_MenuControllerSupport_Up;
        public InputActionMap Get() { return m_Wrapper.m_MenuControllerSupport; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuControllerSupportActions set) { return set.Get(); }
        public void SetCallbacks(IMenuControllerSupportActions instance)
        {
            if (m_Wrapper.m_MenuControllerSupportActionsCallbackInterface != null)
            {
                @Up.started -= m_Wrapper.m_MenuControllerSupportActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_MenuControllerSupportActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_MenuControllerSupportActionsCallbackInterface.OnUp;
            }
            m_Wrapper.m_MenuControllerSupportActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
            }
        }
    }
    public MenuControllerSupportActions @MenuControllerSupport => new MenuControllerSupportActions(this);
    public interface IMenuControllerSupportActions
    {
        void OnUp(InputAction.CallbackContext context);
    }
}
